######################################################################
# Redmine develop docker-compose
#
# 作成日：2020/07/07 作成者：akihiro.toda
# 更新日：2020/07/17 更新者：akihiro.toda
#
# Copyright (c)  Inc. - All rights reserved.
######################################################################

version: "3.7"

services:
  redmine-app:
    build: ./app/develop
    container_name: redmine-app
    restart: always
    ports:
      - 8080:3000
    environment:
      # 必要な場合
      # HTTP_PROXY: http://xxxxxx@txxxx.com:xxxxxx@proxy:8080
      # HTTPS_PROXY: http://xxxxxx@xxxxx.com:xxxxxx@prxoy:8080
      TZ: Asia/Tokyo
    env_file: ./app/config/db.env
    volumes:
      - ./app/files:/usr/src/redmine/files
      - ./app/log/:/usr/src/redmine/log
      - ./app/public/themes:/usr/src/redmine/public/themes
    networks:
      redminenet:
        ipv4_address: 172.11.0.3

  redmine-db:
    build: ./db/develop
    container_name: redmine-db
    restart: always
    environment:
      # 必要な場合
      # HTTP_PROXY: http://xxxxxx@txxxx.com:xxxxxx@proxy:8080
      # HTTPS_PROXY: http://xxxxxx@xxxxx.com:xxxxxx@prxoy:8080
      TZ: Asia/Tokyo
    env_file: ./db/config/db.env
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/result:/var/lib/mysql-files
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    networks:
      redminenet:
        ipv4_address: 172.11.0.4

networks:
  redminenet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.11.0.0/24
